name: blog_app
description: "Blog App"
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  fpdart: ^1.1.0
  gap: ^3.0.1
  get_it: ^8.0.0
  image_picker: ^1.1.2
  supabase_flutter: ^2.6.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  package_rename: ^1.7.1

flutter:
  uses-material-design: true
  assets:
    - .env

package_rename_config:
  android:
    app_name: Blog App
    package_name: com.yuceal.blog_app

  ios:
    app_name: Blog App
    bundle_name: com.yuceal.blog_app
    package_name: com.yuceal.blog_app
